DemoCafe/Models/CafeContext.cs
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;

namespace DemoCafe.Models
{
    public class CafeContext : DbContext
    {
        public CafeContext(DbContextOptions<CafeContext> options) : base(options)

        {
        }

        public DbSet<NhanSu> NhanSus { get; set; }
        public DbSet<KhoHang> KhoHangs { get; set; }
        public DbSet<ThuChi>ThuChis { get; set; }
    }
}

DemoCafe/Models/ErrorViewModel.cs
using System;

namespace DemoCafe.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DemoCafe/Models/KhoHang.cs
using System.ComponentModel.DataAnnotations;

namespace DemoCafe.Models
{
    public class KhoHang
    {
        [Key]
        public int IdStt { get; set; }
        public string NLPhaChe { get; set; }
        public string DungCu { get; set; }
    }
}

DemoCafe/Models/NhanSu.cs
using System.ComponentModel.DataAnnotations;

namespace DemoCafe.Models
{
    public class NhanSu
    {
        [Key]
        public int IdMaNhanVien { get; set; }
        public string FulllName { get; set; }
        public string Sdt { get; set; }
    }
}

DemoCafe/Models/ThuChi.cs
using System.ComponentModel.DataAnnotations;

namespace DemoCafe.Models
{
    public class ThuChi
    {
        [Key]
        public int IdMaDonHang { get; set; }
        public string TenHang { get; set; }
        public string SoLuong { get; set; }
        public float DoanhThu { get; set; }
        public float ChiTieu { get; set; }
    }
}

DemoCafe/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DemoCafe.Models;

namespace DemoCafe.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }
    }
}

DemoCafe/Controllers/KhoHangController.cs
using DemoCafe.Models;
using DemoCafe.Services.KhoHang;
using Microsoft.AspNetCore.Mvc;

namespace DemoCafe.Controllers
{
    public class KhoHangController : Controller
    {
        private readonly IKhoHangService _khoHangService;

        public KhoHangController(IKhoHangService khoHangService)
        {
            _khoHangService = khoHangService;
        }
        // GET
        [HttpGet]
        public IActionResult Index()
        {
            return
            View(_khoHangService.GetAll());
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(KhoHang khoHang)
        {
            _khoHangService.Add(khoHang);
            _khoHangService.Save();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var getId = _khoHangService.GetById(id);
            return View(getId);
        }

        [HttpPost]
        public IActionResult Edit(KhoHang khoHang)
        {
            _khoHangService.Update(khoHang);
            _khoHangService.Save();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            _khoHangService.Delete(id);
            _khoHangService.Save();
            return RedirectToAction("Index");
        }
    }
}

DemoCafe/Controllers/NhanSuController.cs
using DemoCafe.Models;
using DemoCafe.Services.NhanSu;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Rewrite.Internal.UrlActions;

namespace DemoCafe.Controllers
{
    public class NhanSuController : Controller
    {
        private readonly INhanSuService _nhanSuService;

        public NhanSuController(INhanSuService nhanSuService)
        {
            _nhanSuService = nhanSuService;
        }
        // GET
        [HttpGet]
        public IActionResult Index()
        {
            return
            View(_nhanSuService.GetAll());
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(NhanSu nhanSu)
        {
            _nhanSuService.Add(nhanSu);
            _nhanSuService.Save();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var getId = _nhanSuService.GetById(id);
            return View(getId);
        }
        [HttpPost]
        public IActionResult Edit(NhanSu nhanSu)
        {
            _nhanSuService.Update(nhanSu);
            _nhanSuService.Save();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            _nhanSuService.Delete(id);
            _nhanSuService.Save();
            return RedirectToAction("Index");
        }
    }
}

DemoCafe/Controllers/ThuChiController.cs
using DemoCafe.Models;
using DemoCafe.Services.ThuChi;
using Microsoft.AspNetCore.Mvc;

namespace DemoCafe.Controllers
{
    public class ThuChiController : Controller
    {
        private readonly IThuChiService _thuChiService;

        public ThuChiController(IThuChiService thuChiService)
        {
            _thuChiService = thuChiService;
        }
        // GET
        [HttpGet]
        public IActionResult Index()
        {
            return
            View(_thuChiService.GetAll());
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(ThuChi thuChi)
        {
            _thuChiService.Add(thuChi);
            _thuChiService.Save();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var getId = _thuChiService.GetById(id);
            return View(getId);
        }

        [HttpPost]
        public IActionResult Edit(ThuChi thuChi)
        {
            _thuChiService.Update(thuChi);
            _thuChiService.Save();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            _thuChiService.Delete(id);
            _thuChiService.Save();
            return RedirectToAction();
        }
    }
}

DemoCafe/Pages/KhoHang/Edit.cshtml
@model object

<!DOCTYPE html>

<html>
<head>
    <title>title</title>
</head>
<body>
<div>
      
</div>
</body>
</html>

DemoCafe/Pages/KhoHang/Index.cshtml
@model System.Collections.Generic.IEnumerable<DemoCafe.Models.KhoHang>

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>title</h2>

DemoCafe/Pages/NhanSu/Edit.cshtml
@model $model$

<!DOCTYPE html>

<html>
<head>
  <title>$title$</title>
</head>
<body>
  <div>
    $END$  
  </div>
</body>
</html>

DemoCafe/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

DemoCafe/Views/KhoHang/Create.cshtml
@model KhoHang

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="NLPhaChe" class="control-label"></label>
                    <input asp-for="NLPhaChe" class="form-control" />
                    <span asp-validation-for="NLPhaChe" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="DungCu" class="control-label"></label>
                    <input asp-for="DungCu" class="form-control" />
                    <span asp-validation-for="DungCu" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                    <a class="text-dark btn btn-primary" asp-area="" asp-controller="KhoHang" asp-action="Index">Back</a>
                </div>
            </form>
        </div>
    </div>
</div>

DemoCafe/Views/KhoHang/Edit.cshtml
@model KhoHang

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-12">
            <form method="post" asp-controller="KhoHang" asp-action="Edit">
                <input type="hidden" class="form-control" asp-for="IdStt">
                <div class="form-group">
                    <label asp-for="NLPhaChe" class="control-label"></label>
                    <input asp-for="NLPhaChe" class="form-control" />
                    <span asp-validation-for="NLPhaChe" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="DungCu" class="control-label"></label>
                    <input asp-for="DungCu" class="form-control" />
                    <span asp-validation-for="DungCu" class="text-danger"></span>
                </div>
                <input class="btn btn-primary" type="submit" value="Save"/>
                <a class=" text-dark btn btn-primary" asp-area="" asp-controller="KhoHang" asp-action="Index">Back</a>
            </form>
        </div>
    </div>
    
</div>

DemoCafe/Views/KhoHang/Index.cshtml
@model IEnumerable<KhoHang>

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<div class="m-auto">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Request List</h2>
                        <a asp-action="Create" class="btn btn-primary">KhoHang</a>

                    </div>
                    <div class="x_content">
                        <table class="table">
                            <thead>
                            <tr>
                                <th>Sender</th>
                                <th>Receiver</th>
                                <th>Content </th>
                                <th>Note </th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach (var item in Model)
                            {
                             
                                <tr class="text-left">
                                    @* <td> @Html.DisplayFor(modelItem => item.SttId)</td> *@
                                    <td> @Html.DisplayFor(modelItem => item.NLPhaChe)</td>
                                    <td> @Html.DisplayFor(modelItem => item.DungCu)</td>
                                   
                                    <td>
                                        <a class="btn btn-primary" asp-action="Edit" asp-route-id="@item.IdStt">Edit</a>
                                        <a class="btn btn-primary" asp-action="Delete" asp-route-id="@item.IdStt">Delete</a>  
                                    </td>
                                </tr>
                            }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

DemoCafe/Views/NhanSu/Create.cshtml
@model NhanSu

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="FulllName" class="control-label"></label>
                    <input asp-for="FulllName" class="form-control" />
                    <span asp-validation-for="FulllName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Sdt" class="control-label"></label>
                    <input asp-for="Sdt" class="form-control" />
                    <span asp-validation-for="Sdt" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                    <a class="text-dark btn btn-primary" asp-area="" asp-controller="NhanSu" asp-action="Index">Back</a>
                </div>
            </form>
        </div>
    </div>
</div>

DemoCafe/Views/NhanSu/Edit.cshtml
@model NhanSu

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-12">
            <form method="post" asp-controller="NhanSu" asp-action="Edit">
                <input type="hidden" class="form-control" asp-for="IdMaNhanVien">
                <div class="form-group">
                    <label asp-for="FulllName" class="control-label"></label>
                    <input asp-for="FulllName" class="form-control" />
                    <span asp-validation-for="FulllName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Sdt" class="control-label"></label>
                    <input asp-for="Sdt" class="form-control" />
                    <span asp-validation-for="Sdt" class="text-danger"></span>
                </div>
d                <input class="btn btn-primary" type="submit" value="Save"/>
                <a class=" text-dark btn btn-primary" asp-area="" asp-controller="NhanSu" asp-action="Index">Back</a>
            </form>
        </div>
    </div>
    
</div>

DemoCafe/Views/NhanSu/Index.cshtml
@model IEnumerable<NhanSu>

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<div class="m-auto">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Request List</h2>
                        <a asp-action="Create" class="btn btn-primary">NhanSu</a>

                    </div>
                    <div class="x_content">
                        <table class="table">
                            <thead>
                            <tr>
                                <th>Sender</th>
                                <th>Receiver</th>
                                <th>Content </th>
                                <th>Note </th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach (var item in Model)
                            {
                             
                                <tr class="text-left">
                                    @* <td> @Html.DisplayFor(modelItem => item.MaNhanVienId)</td> *@
                                    <td> @Html.DisplayFor(modelItem => item.FulllName)</td>
                                    <td> @Html.DisplayFor(modelItem => item.Sdt)</td>
                                   
                                    <td>
                                        <a class="btn btn-primary" asp-action="Edit" asp-route-id="@item.IdMaNhanVien">Edit</a>
                                        <a class="btn btn-primary" asp-action="Delete" asp-route-id="@item.IdMaNhanVien">Delete</a>  
                                    </td>
                                </tr>
                            }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

DemoCafe/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DemoCafe</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="NhanSu" asp-action="Index">DemoCafe</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="NhanSu" asp-action="Create">ThanhVien</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="NhanSu" asp-action="Edit">ThemXoaNS</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ThuChi" asp-action="Create">TaoDoanhThu</a>
                        </li>
                       i>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ThuChi" asp-action="Edit">UpdateDoanhThu</a>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="KhoHang" asp-action="Create">NhapHang</a>
                            </li>
                            
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - DemoCafe - <a asp-area="" asp-controller="NhanSu" asp-action="Index">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

DemoCafe/Views/ThuChi/Create.cshtml
@model ThuChi

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="TenHang" class="control-label"></label>
                    <input asp-for="TenHang" class="form-control" />
                    <span asp-validation-for="TenHang" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ChiTieu" class="control-label"></label>
                    <input asp-for="ChiTieu" class="form-control" />
                    <span asp-validation-for="ChiTieu" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="SoLuong" class="control-label"></label>
                    <input asp-for="SoLuong" class="form-control" />
                    <span asp-validation-for="SoLuong" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="DoanhThu" class="control-label"></label>
                    <input asp-for="DoanhThu" class="form-control" />
                    <span asp-validation-for="DoanhThu" class="text-danger"></span>
                </div>
              <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                    <a class="text-dark btn btn-primary" asp-area="" asp-controller="ThuChi" asp-action="Index">Back</a>
                </div>
            </form>
        </div>
    </div>
</div>

DemoCafe/Views/ThuChi/Edit.cshtml
@model ThuChi

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-12">
            <form method="post" asp-controller="ThuChi" asp-action="Edit">
                <input type="hidden" class="form-control" asp-for="IdMaDonHang">
                <div class="form-group">
                    <label asp-for="TenHang" class="control-label"></label>
                    <input asp-for="TenHang" class="form-control" />
                    <span asp-validation-for="TenHang" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ChiTieu" class="control-label"></label>
                    <input asp-for="ChiTieu" class="form-control" />
                    <span asp-validation-for="ChiTieu" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="SoLuong" class="control-label"></label>
                    <input asp-for="SoLuong" class="form-control" />
                    <span asp-validation-for="SoLuong" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="DoanhThu" class="control-label"></label>
                    <input asp-for="DoanhThu" class="form-control" />
                    <span asp-validation-for="DoanhThu" class="text-danger"></span>
                </div>
                <input class="btn btn-primary" type="submit" value="Save"/>
                <a class=" text-dark btn btn-primary" asp-area="" asp-controller="ThuChi" asp-action="Index">Back</a>
            </form>
        </div>
    </div>
    
</div>

DemoCafe/Views/ThuChi/Index.cshtml
@model IEnumerable<ThuChi>

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<div class="m-auto">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Request List</h2>
                        <a asp-action="Create" class="btn btn-primary">ThuChi</a>

                    </div>
                    <div class="x_content">
                        <table class="table">
                            <thead>
                            <tr>
                                <th>Sender</th>
                                <th>Receiver</th>
                                <th>Content </th>
                                <th>Note </th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach (var item in Model)
                            {
                             
                                <tr class="text-left">
                                    @* <td> @Html.DisplayFor(modelItem => item.MaDonHangId)</td> *@
                                    <td> @Html.DisplayFor(modelItem => item.TenHang)</td>
                                    <td> @Html.DisplayFor(modelItem => item.ChiTieu)</td>
                                    <td> @Html.DisplayFor(modelItem=>item.SoLuong)</td>
                                    <td> @Html.DisplayFor(modelItem=>item.DoanhThu)</td>
                                   
                                    <td>
                                        <a class="btn btn-primary" asp-action="Edit" asp-route-id="@item.IdMaDonHang">Edit</a>
                                        <a class="btn btn-primary" asp-action="Delete" asp-route-id="@item.IdMaDonHang">Delete</a>  
                                    </td>
                                </tr>
                            }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>